// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/cullinary/cull-1.tsx";
import * as $4 from "./routes/cullinary/cull-2.tsx";
import * as $5 from "./routes/cullinary/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/GameFrame.tsx";
import * as $$2 from "./islands/MainHeaderContent.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/cullinary/cull-1.tsx": $3,
    "./routes/cullinary/cull-2.tsx": $4,
    "./routes/cullinary/index.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/GameFrame.tsx": $$1,
    "./islands/MainHeaderContent.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
